#!/usr/bin/env python3
# BakeManage IP Assignment: All contributions assign IP to BakeManage (c) 2026
"""
inject_secrets.py — Vault-backed secret injection for BakeManage.

Status: 🔷 CODED (AGAM-ready for post-May Olympus deployment)

Behaviour:
  1. If VAULT_ADDR and VAULT_TOKEN are set → fetch secrets from HashiCorp Vault
     at path: kv/antigravity/<OLYMPUS_APP_NAME>/<key>
  2. Fallback → read from existing environment variables (cloud-first dev mode)
  3. Writes a .env file to the working directory with resolved values.

Usage (AGAM on Atlas or LXC 199):
  export VAULT_ADDR=https://vault.olympus.ai
  export VAULT_TOKEN=<runtime-token>
  export OLYMPUS_APP_NAME=bakemanage
  python3 scripts/inject_secrets.py

Vault path convention: kv/antigravity/bakemanage/<key>
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

# Keys to resolve — maps .env variable name → Vault secret key
_SECRET_KEYS: dict[str, str] = {
    "JWT_SECRET": "jwt_secret",
    "DEFAULT_ADMIN_PIN": "default_admin_pin",
    "BOOTSTRAP_PIN": "bootstrap_pin",
    "DATABASE_URL": "database_url",
    "FERNET_KEY": "fernet_key",
    "GAIS_BM_APIK": "gais_bm_apik",
}

# Keys that are safe to include from environment without Vault (non-secret config)
_CONFIG_KEYS: list[str] = [
    "CELERY_BROKER_URL",
    "CELERY_RESULT_BACKEND",
    "REDIS_URL",
    "ENVIRONMENT",
    "JWT_EXPIRY_MINUTES",
    "DEFAULT_ADMIN_USERNAME",
    "OLYMPUS_APP_NAME",
    "VAULT_ADDR",
    "DIPLOMAT_URL",
    "SSO_ENFORCE",
]


def _fetch_from_vault(app_name: str, vault_addr: str, vault_token: str) -> dict[str, str]:
    """Attempt to read secrets from HashiCorp Vault KV v2."""
    try:
        import hvac  # type: ignore[import]
    except ImportError:
        print("[inject_secrets] hvac not installed — falling back to environment variables.", file=sys.stderr)
        return {}

    client = hvac.Client(url=vault_addr, token=vault_token)
    if not client.is_authenticated():
        print("[inject_secrets] Vault authentication failed — falling back to environment variables.", file=sys.stderr)
        return {}

    resolved: dict[str, str] = {}
    for env_var, vault_key in _SECRET_KEYS.items():
        path = f"antigravity/{app_name}/{vault_key}"
        try:
            secret = client.secrets.kv.v2.read_secret_version(path=path)
            value = secret["data"]["data"].get(vault_key, "")
            if value:
                resolved[env_var] = value
        except Exception as exc:  # noqa: BLE001
            # Log only the exception type — do not log path, value, or secret identifiers to avoid leaking secret metadata
            print(f"[inject_secrets] Warning: could not read one or more Vault keys (error type: {type(exc).__name__})", file=sys.stderr)
    return resolved


def _fetch_from_env() -> dict[str, str]:
    """Read secrets from environment variables (cloud-first dev fallback)."""
    return {k: os.environ[k] for k in _SECRET_KEYS if k in os.environ}


def _build_env_file(secrets: dict[str, str]) -> str:
    """Build .env file content from resolved secrets and config keys."""
    lines: list[str] = [
        "# Generated by scripts/inject_secrets.py — DO NOT COMMIT",
        "# Secrets sourced from Vault or environment — rotate via Vault if on Olympus platform",
        "",
    ]
    for key in _CONFIG_KEYS:
        value = os.environ.get(key, "")
        if value:
            lines.append(f"{key}={value}")

    lines.append("")
    lines.append("# Secrets (Vault-injected or env-fallback)")
    for env_var in _SECRET_KEYS:
        value = secrets.get(env_var, "")
        if value:
            lines.append(f"{env_var}={value}")
        else:
            lines.append(f"# {env_var}=<not-resolved>")

    return "\n".join(lines) + "\n"


def main() -> None:
    vault_addr = os.environ.get("VAULT_ADDR", "")
    vault_token = os.environ.get("VAULT_TOKEN", "")
    app_name = os.environ.get("OLYMPUS_APP_NAME", "bakemanage")
    output_path = Path(os.environ.get("ENV_OUTPUT_PATH", ".env"))

    if vault_addr and vault_token:
        print(f"[inject_secrets] Fetching secrets from Vault at {vault_addr} for app '{app_name}'...")
        secrets = _fetch_from_vault(app_name, vault_addr, vault_token)
        if secrets:
            print(f"[inject_secrets] Resolved {len(secrets)}/{len(_SECRET_KEYS)} secrets from Vault.")
        else:
            print("[inject_secrets] Vault fetch returned no secrets — falling back to environment.")
            secrets = _fetch_from_env()
    else:
        print("[inject_secrets] VAULT_ADDR/VAULT_TOKEN not set — using environment variables (dev mode).")
        secrets = _fetch_from_env()

    env_content = _build_env_file(secrets)
    # Write with owner-only permissions (0o600) — this file contains sensitive secrets
    output_path.touch(mode=0o600, exist_ok=True)
    output_path.write_text(env_content, encoding="utf-8")
    output_path.chmod(0o600)
    print(f"[inject_secrets] Wrote {output_path.resolve()} (mode 0600)")


if __name__ == "__main__":
    main()
